// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCPP.Core.Database;

#nullable disable

namespace OCPP.Core.Database.Migrations
{
    [DbContext(typeof(OCPPCoreContext))]
    partial class OCPPCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("OCPP.Core.Database.ChargePoint", b =>
                {
                    b.Property<string>("ChargePointId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCertThumb")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ChargePointId");

                    b.HasIndex(new[] { "ChargePointId" }, "ChargePoint_Identifier")
                        .IsUnique();

                    b.ToTable("ChargePoint", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargeTag", b =>
                {
                    b.Property<string>("TagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Blocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentTagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("TagId")
                        .HasName("PK_ChargeKeys");

                    b.ToTable("ChargeTags");
                });

            modelBuilder.Entity("OCPP.Core.Database.ConnectorStatus", b =>
                {
                    b.Property<string>("ChargePointId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastMeter")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastMeterTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastStatusTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ChargePointId", "ConnectorId");

                    b.ToTable("ConnectorStatus", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.MessageLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex(new[] { "LogTime" }, "IX_MessageLog_ChargePointId");

                    b.ToTable("MessageLog", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeterStart")
                        .HasColumnType("REAL");

                    b.Property<double?>("MeterStop")
                        .HasColumnType("REAL");

                    b.Property<string>("StartResult")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopTagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("ChargePointId", "ConnectorId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OCPP.Core.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.UserChargePoint", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("UserId", "ChargePointId");

                    b.HasIndex("ChargePointId");

                    b.ToTable("UserChargePoints", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.UserChargeTag", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TagId");

                    b.HasIndex("TagId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserChargeTags", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.ConnectorStatus", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargePoint", "ChargePoint")
                        .WithMany()
                        .HasForeignKey("ChargePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePoint");
                });

            modelBuilder.Entity("OCPP.Core.Database.Transaction", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargePoint", "ChargePoint")
                        .WithMany("Transactions")
                        .HasForeignKey("ChargePointId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_ChargePoint");

                    b.Navigation("ChargePoint");
                });

            modelBuilder.Entity("OCPP.Core.Database.UserChargePoint", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargePoint", "ChargePoint")
                        .WithMany("UserChargePoints")
                        .HasForeignKey("ChargePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OCPP.Core.Database.User", "User")
                        .WithMany("UserChargePoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OCPP.Core.Database.UserChargeTag", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargeTag", "ChargeTag")
                        .WithMany("UserChargeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OCPP.Core.Database.User", "User")
                        .WithMany("UserChargeTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargeTag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargePoint", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("UserChargePoints");
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargeTag", b =>
                {
                    b.Navigation("UserChargeTags");
                });

            modelBuilder.Entity("OCPP.Core.Database.User", b =>
                {
                    b.Navigation("UserChargePoints");

                    b.Navigation("UserChargeTags");
                });
#pragma warning restore 612, 618
        }
    }
}
